apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    extensions:
    - extension:
        last-update: <DATE>
        provider: minikube.sigs.k8s.io
        version: v1.38.1
      name: cluster_info
    server: https://host.docker.internal:<YOUR_MINIKUBE_PORT>
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
users:
- name: minikube
  user:
    client-certificate-data: <BASE64_ENCODED_CLIENT_CERTIFICATE>
    client-key-data: <BASE64_ENCODED_CLIENT_KEY>
