@Library('shared-library') _

pipeline {
    agent {
        label 'devops-agent'
    }
    stages {
        stage('BuildApp') {
            steps {
                buildApp(workingDir: '04-Jenkins/Lab23-Jenkins-Shared-Library')
            }
        }
        stage('BuildImage') {
            steps {
                buildImage(
                    workingDir: '04-Jenkins/Lab23-Jenkins-Shared-Library',
                    imageName: 'myapp'
                )
            }
        }
        stage('DeployOnK8s') {
            steps {
                deployOnK8s(
                    workingDir: '04-Jenkins/Lab23-Jenkins-Shared-Library',
                    manifestPath: 'manifests/deployment.yaml'
                )
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed.'
            cleanWs()
        }
        success {
            echo 'Application deployed successfully.'
        }
        failure {
            echo 'Pipeline execution failed.'
        }
    }
}
